server:
  port: 8082

spring:
  application:
    name: shipping-consumer
  profiles:
    active: dev
  kafka:
    consumer:
      bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
      group-id: shipping-consumer
      auto-offset-reset: earliest
    producer:
      bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
  main:
    web-application-type: reactive
kafka:
  topic: orders
  auto-offset-reset: earliest