server:
  port: 8080

kafka:
  topic: orders

spring:
  profiles:
    active: dev
  kafka:
    producer:
      bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
    admin: # enables runtime creation of topics. not for production
      properties:
        bootstrap.servers: localhost:9092, localhost:9093, localhost:9094
  main:
    web-application-type: reactive